name: MacOS

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Get Ninja
        run: brew install ninja && ninja --version

      - name: Fetch repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Build
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: clang
          cxx: clang++
          configure-options: -v -G Ninja -Daudacity_use_wxwidgets:STRING=local
          build-type: Release
          parallel: 8
